name = "email-generator-worker"
main = "src/server/worker.ts"
compatibility_date = "2025-10-10"

[[routes]]
pattern = "email-generator-worker.my-domain.com"
custom_domain = true

[observability]
enabled = true
head_sampling_rate = 1